language: python

jobs:
  include:
    # perform a linux build
    - services: docker
      env: PIP=pip
    # and a mac build
    - os: osx
      language: shell
      env: PIP=pip3
    # and a windows build
    - os: windows
      language: shell
      env: PIP=pip3
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

env:
    global:
        CIBW_BUILD=cp36-* cp37-* cp38-*

script:
  # build the wheels, put them into './wheelhouse'
  - $PIP install cibuildwheel==1.3.0
  - $PIP install Cython numpy
  - python3 -m cibuildwheel --output-dir wheelhouse
