dist: xenial   # required for Python >= 3.7
language: python

# lists all jobs to be run (with conditions depending on the setup: ie. making a release or updating develop)
matrix:
  include:
# release setup (builds wheels for Python 3.[6,7,8] on OSX, Windows and ManyLinux)
      # and a mac build (see https://cibuildwheel.readthedocs.io/en/stable/)
        - if: branch = junk
          os: osx
          language: shell
          install:
            - brew install llvm libomp
            - export CPP=/usr/local/opt/llvm/bin/clang;
            - python3 -m pip install cibuildwheel==1.3.0
          env:
            - CIBW_BEFORE_BUILD="pip install -r requirements_dev.txt && pip install ."
            - CIBW_BUILD="cp36-* cp37-* cp38-*"
            - CIBW_SKIP=*-manylinux*
            - HOMEBREW_NO_AUTO_UPDATE=1
          script:
              # build the wheels, put them into './wheelhouse'
              - python3 -m cibuildwheel --output-dir wheelhouse
              - ls wheelhouse/
          after_success:
              - |
                if [[ $TRAVIS_TAG ]]; then
                  python3 -m pip install twine
                  python3 -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
                fi

